development: &development
  adapter: postgresql
  database: geodemo_development
  host: localhost
  pool: 5
  username: o1
  password: com99123
  timeout: 5000
  encoding: utf8
  min_messages: warning
  template: template_postgis

test:
  <<: *development
  database: geodemo_test

production:
  <<: *development
  host: galileo.codeifier.com
  database: geodemo_production
  username: deployment
  password: FireDrake[1981]